# 17 
Дана целочисленная прямоугольная матрица. Определить:

количество строк, содержащих хотя бы один нулевой элемент;

номер столбца, в котором находится самая длинная серия одинаковых элементов.

In [114]:
import numpy as np


m = np.matrix('1 1 0 4; 5 1 0 8; 9 1 1 12')
print(m, np.sum(np.any(m == 0, axis = 1)))

[[ 1  1  0  4]
 [ 5  1  0  8]
 [ 9  1  1 12]] 2


In [115]:
print(np.argmax(np.sum((np.diff(m, axis=0) == 0).astype(np.int32), axis=0)))

1
